import jsPDF from "jspdf";

export function downloadAsPDF(title: string, content: string, filename: string) {
  const doc = new jsPDF();
  
  // Add header
  doc.setFontSize(16);
  doc.setTextColor(37, 99, 235); // Blue color
  doc.text("Generated by ScholarShield", 14, 20);
  
  // Add title
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text(title, 14, 35);
  
  // Add content
  doc.setFontSize(11);
  const lines = doc.splitTextToSize(content, 180); // 180mm width
  doc.text(lines, 14, 45);
  
  // Save the PDF
  doc.save(filename);
}

